### ISSUE TITLE
Language flags not aligned left on annotation page 

### ISSUE THREAD

**Issue by LaraHack** [rasvaan/accurator#105]
![languageflagscenteredinsteadofalignedleft](https://cloud.githubusercontent.com/assets/8199152/10192480/ed68b60a-677c-11e5-83f7-e86f918d3343.jpg)

**Comment by rasvaan** [comment]
Solved while updating the page:
![screen shot 2016-01-20 at 12 14 29](https://cloud.githubusercontent.com/assets/1213099/12447290/657cd924-bf6f-11e5-9972-f8f530ac510d.png)
