### ISSUE TITLE
Problems in addPath in accurator_annotate.js due to the changes in results page

### ISSUE THREAD

**Issue by LaraHack** [rasvaan/accurator#158]
function addPath() {
    query = localStorage.getItem("query");
    var cluster = JSON.parse(localStorage.getItem("currentCluster"));
    $("#path").append(pathHtmlElements(cluster.path));
    unfoldPathEvent("#path", cluster.path);
    addClusterNavigationButtonEvents();
}

ReferenceError: pathHtmlElements is not defined -> line 89 in accurate_annotate.js 

Also, "currentCluster" is not present in localStorage

**Comment by rasvaan** [comment]
Not relevant anymore since introduction path objects.
