### ISSUE TITLE
Random list of results not persistent

### ISSUE THREAD

**Issue by LaraHack** [rasvaan/accurator#181]
Population of the random list of objects should be done in a persistent way, not only by using HTML code for rendering them. See populateRandom function in accurator_results.js.

**Comment by rasvaan** [comment]
This is the 'random cluster' added to the recommended items:
https://github.com/rasvaan/accurator/blob/search/web/js/accurator_results.js#L161
My preference would be to replace populateRandom, instead invoke the random function, making the number of retrieved random objects a variable:
https://github.com/rasvaan/accurator/blob/search/web/js/accurator_results.js#L192
Keep in mind, this function is used only to add a new cluster (/row) to the recommended items.
