### ISSUE TITLE
Possibly a field as "Style Period" or "Related subject" could be interesting

### ISSUE THREAD

**Issue by Ykje** [rasvaan/accurator#246]
Just an idea: especially when the (fashion item) data is already rich. This kind of info would actually be interesting for the museum database as well. Maybe from Wikidata :)

**Comment by rasvaan** [comment]
Thanks, suggestions for fields are more than welcome. I will create multiple sub topics in the fashion domain (paintings, jewellery, shoes) and depending on the sub topic we will have to find the right balance of fields.
