### ISSUE TITLE
Email explanation

### ISSUE THREAD

**Issue by rasvaan** [rasvaan/accurator#52]
Note for which goals we will use the email address.

**Comment by LWessels** [comment]
What do you think about this?

Gegevens die u aan SEALINCMedia verstrekt worden zorgvuldig en vertrouwelijk behandeld. Persoonsgegevens worden uitsluitend gebruikt voor wetenschappelijke doeleinden en worden niet verstrekt aan derden. SEALINCMedia conformeert zich aan de Wet Bescherming Persoonsgegevens.

The information you provide to SEALINCMedia is being handled with the utmost care. Personal information is exclusively used for scientific purposes and will not be shared with other parties. SEALINCMedia is committed to the Dutch Law on the protection of personal information (Wet Bescherming Persoonsgegevens).
