### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by LWessels** [rasvaan/accurator#68]
The phrase 'tagging' might not be known by every user. I would suggest  to add a short description of what tagging is.
![2 jpeg](https://cloud.githubusercontent.com/assets/11662463/6846830/50ecdc72-d3b9-11e4-9f71-6b3203b72f25.jpg)

**Comment by rasvaan** [comment]
In the ornithologists user experiment we discussed changing it to 'informatie toe te voegen aan afbeeldingen'. That ok, or to general?

**Comment by LWessels** [comment]
I would rather add 'informatie toevoegen aan afbeeldingen' as a description of tagging, than replacing the word itself. Experienced Facebook-users would immediately recognise the word tagging.
