### ISSUE TITLE
Pages which contain exclusively text

### ISSUE THREAD

**Issue by LWessels** [rasvaan/accurator#90]
Chris, you have probably already noticed this, but there are several pages which contain exclusively text and no illustrations in Accurator. These are from Taferelen der voornaamste geschiedenissen [...]. Is it possible to remove these pages?

**Comment by rasvaan** [comment]
There are also empty pages :( At the moment I automatically selected every page within the UBVU bible collection, but we could also make a hand curated list. I propose to leave it like this, these pages will only pop up in the random cluster, just advice annotators to skip over them. 

At the moment you feel like you have nothing to do anymore give me a heads up, I can send you a file from which you can remove the uris which have only text/are blanc.
