### ISSUE TITLE
Locale changes after registering

### ISSUE THREAD

**Issue by rasvaan** [rasvaan/accurator#97]
The locale changed upon registering (from register in en, it switched to additional information in nl).

**Comment by LaraHack** [comment]
The annotation fields are in a different language than the one chosen by the user. The menus and the buttons are in the chosen language, but the annotation controller is not. In this particular case, the chosen language was English and the fields in the annotation controller were in Dutch.

![controlerignoresgenerallanguagechosen](https://cloud.githubusercontent.com/assets/8199152/9812000/be7e8f7e-587a-11e5-8ae2-eb86de01380f.png)

**Comment by rasvaan** [comment]
Reproduced on local machine on Firefox (starting from setting ?locale=nl at register screen, register, and then the additional info screen turns up in english). While registering the locale is not saved to Cliopatria, only to the local storage. To fix, add locale to database at the time the user registers.
